In [1]:
import numpy as np

# Three songs represented as vectors [energy, danceability, acousticness]
blinding_lights = np.array([0.73, 0.51, 0.00])  # The Weeknd
levitating = np.array([0.69, 0.70, 0.03])        # Dua Lipa
someone_like_you = np.array([0.34, 0.50, 0.75])  # Adele

def similarity(song_a, song_b):
    """Cosine similarity - how similar are two vectors?"""
    return np.dot(song_a, song_b) / (np.linalg.norm(song_a) * np.linalg.norm(song_b))

print(f"Blinding Lights vs Levitating: {similarity(blinding_lights, levitating):.2f}")
print(f"Blinding Lights vs Someone Like You: {similarity(blinding_lights, someone_like_you):.2f}")

# Output:
# Blinding Lights vs Levitating: 0.94  (very similar! both are upbeat pop)
# Blinding Lights vs Someone Like You: 0.54  (less similar - different vibes)

Blinding Lights vs Levitating: 0.98
Blinding Lights vs Someone Like You: 0.59


# dot product visualize

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider

def visualize_dot_product(angle_degrees=45):
    # Fixed vector a
    a = np.array([1, 0])
    
    # Vector b at specified angle
    angle_rad = np.radians(angle_degrees)
    b = np.array([np.cos(angle_rad), np.sin(angle_rad)])
    
    # Dot product
    dot = np.dot(a, b)

    # Plot
    plt.figure(figsize=(8, 6))
    plt.quiver(0, 0, a[0], a[1], angles='xy', scale_units='xy',
               scale=1, color='blue', label='Vector a')
    plt.quiver(0, 0, b[0], b[1], angles='xy', scale_units='xy',
               scale=1, color='red', label='Vector b')

    plt.xlim(-1.5, 1.5)
    plt.ylim(-1.5, 1.5)
    plt.grid(True, alpha=0.3)
    plt.axhline(0, color='k', linewidth=0.5)
    plt.axvline(0, color='k', linewidth=0.5)

    plt.title(
        f'Angle: {angle_degrees}° | '
        f'Dot Product: {dot:.3f} | '
        f'cos({angle_degrees}°) = {np.cos(angle_rad):.3f}'
    )

    plt.legend()
    plt.axis('equal')
    plt.show()

# Interactive slider (Jupyter Notebook)
interact(
    visualize_dot_product,
    angle_degrees=FloatSlider(min=0, max=360, step=5, value=45)
)


interactive(children=(FloatSlider(value=45.0, description='angle_degrees', max=360.0, step=5.0), Output()), _d…

<function __main__.visualize_dot_product(angle_degrees=45)>

In [12]:
import numpy as np

class ApartmentFinder:
    def __init__(self, apartments):
        """
        apartments: dict of {name: [beds, sqft, rent, commute]}
        """
        self.names = list(apartments.keys())
        self.vectors = np.array(list(apartments.values()))
        
        # Normalize for fair comparison
        self.normalized = self._normalize(self.vectors)
    
    def _normalize(self, data):
        mins = data.min(axis=0)
        maxs = data.max(axis=0)
        return (data - mins) / (maxs - mins + 1e-8)  # avoid division by zero
    
    def find_similar(self, query, top_k=3):
        """Find top_k most similar apartments to query."""
        # Normalize the query
        query_norm = (np.array(query) - self.vectors.min(axis=0)) / \
                     (self.vectors.max(axis=0) - self.vectors.min(axis=0) + 1e-8)
        
        # Calculate similarity to all apartments
        similarities = []
        for i, apt in enumerate(self.normalized):
            sim = np.dot(query_norm, apt) / \
                  (np.linalg.norm(query_norm) * np.linalg.norm(apt) + 1e-8)
            similarities.append((self.names[i], sim, self.vectors[i]))
        
        # Sort by similarity (highest first)
        similarities.sort(key=lambda x: x[1], reverse=True)
        
        return similarities[:top_k]

# Database of apartments
listings = {
    'Downtown Loft': [1, 900, 2800, 5],
    'Suburban House': [4, 2200, 3200, 35],
    'Cozy Studio': [0, 500, 1500, 20],
    'Modern 2BR': [2, 1100, 2400, 15],
    'Family Home': [3, 1800, 2900, 25],
    'Luxury Penthouse': [2, 1500, 5500, 10],
    'Budget 1BR': [1, 700, 1800, 30],
    'Midtown 2BR': [2, 1050, 2350, 12],
}

finder = ApartmentFinder(listings)

# What I'm looking for
my_ideal = [2, 1200, 2400, 15]

print("Your search: 2BR, 1200sqft, $2400, 15min commute")
print("\nMost similar apartments:")
for name, similarity, features in finder.find_similar(my_ideal):
    print(f"  {similarity:.2f} - {name}: {int(features[0])}BR, "
          f"{int(features[1])}sqft, ${int(features[2])}, {int(features[3])}min")

Your search: 2BR, 1200sqft, $2400, 15min commute

Most similar apartments:
  1.00 - Modern 2BR: 2BR, 1100sqft, $2400, 15min
  0.99 - Family Home: 3BR, 1800sqft, $2900, 25min
  0.99 - Midtown 2BR: 2BR, 1050sqft, $2350, 12min


In [14]:
def cosine_similarity(v, w):
    """Compute cosine similarity between two vectors."""
    return np.dot(v, w) / (np.linalg.norm(v) * np.linalg.norm(w))

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "machine learning is awesome",
    "deep learning is a subset of machine learning",
    "neural networks are powerful",
    "python is great for machine learning"
]

# Convert to vectors
vectorizer = CountVectorizer()
doc_vectors = vectorizer.fit_transform(documents).toarray()

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nDocument vectors:")
print(doc_vectors)

# Find similar documents to "machine learning"
query = "machine learning"
query_vector = vectorizer.transform([query]).toarray()[0]

for i, doc_vec in enumerate(doc_vectors):
    sim = cosine_similarity(query_vector, doc_vec)
    print(f"Doc {i}: {sim:.3f} - {documents[i]}")

Vocabulary: ['are' 'awesome' 'deep' 'for' 'great' 'is' 'learning' 'machine' 'networks'
 'neural' 'of' 'powerful' 'python' 'subset']

Document vectors:
[[0 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 2 1 0 0 1 0 0 1]
 [1 0 0 0 0 0 0 0 1 1 0 1 0 0]
 [0 0 0 1 1 1 1 1 0 0 0 0 1 0]]
Doc 0: 0.707 - machine learning is awesome
Doc 1: 0.707 - deep learning is a subset of machine learning
Doc 2: 0.000 - neural networks are powerful
Doc 3: 0.577 - python is great for machine learning
